version: "3.5"
services:
  ${repository}:
    image: hatlonely/${repository}:${version}
    hostname: ${repository}
    user: root
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    # ports:
    #   - "8080:8080"
    #   - "50000:50000"
    volumes:
      - "/var/docker/${repository}/data:/var/jenkins_home"
      - "/var/docker:/var/docker"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/bin/docker:/usr/bin/docker"
    networks:
      - ${repository}net
      - mysqlnet

networks:
  ${repository}net:
    name: ${repository}net
  mysqlnet:
    external: true
    name: mysqlnet
